backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Artikel"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "Gambar Sampul", name: "featuredImage", widget: "image" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Konten", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

  - name: "pages"
    label: "Halaman"
    files:
      - file: "src/_data/metadata.json"
        label: "Metadata Website"
        name: "metadata"
        fields:
          - { label: "Judul Website", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }
      
      - file: "src/index.njk"
        label: "Halaman Utama"
        name: "home"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "About Title", name: "aboutTitle", widget: "string" }
          - { label: "About Content", name: "aboutContent", widget: "markdown" }
          - { label: "CTA Text", name: "ctaText", widget: "string" }
          - { label: "CTA Button Text", name: "ctaButtonText", widget: "string" }
          - { label: "CTA Button URL", name: "ctaButtonUrl", widget: "string" }
  
  - name: "team"
    label: "Tim"
    folder: "src/_data/team"
    create: true
    fields:
      - { label: "Nama", name: "name", widget: "string" }
      - { label: "Posisi", name: "position", widget: "string" }
      - { label: "Foto", name: "photo", widget: "image" }
      - { label: "Bio", name: "bio", widget: "text" }
  
  - name: "programs"
    label: "Program"
    folder: "src/_data/programs"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
  
  - name: "gallery"
    label: "Galeri"
    folder: "src/_data/gallery"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Deskripsi", name: "description", widget: "text", required: false }
  
  - name: "timeline"
    label: "Timeline"
    folder: "src/_data/timeline"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "date" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Icon", name: "icon", widget: "image", required: false }
